from pydantic import BaseModel, Field


class Hypothesis(BaseModel):
    """A scientific hypothesis generated by the co-scientist."""

    id: str
    title: str
    description: str
    reasoning: str

    supporting_evidence: list[str] = Field(default_factory=list)
    contradictory_evidence: list[str] = Field(default_factory=list)

    testable_prediction: str

    elo_rating: float = 1000.0
    generation: int = 0


class HypothesisBatch(BaseModel):
    """A collection of hypotheses produced in one generation round."""

    hypotheses: list[Hypothesis]


class HypothesisReview(BaseModel):
    """A peer review of a scientific hypothesis."""

    hypothesis_id: str

    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)

    plausibility_score: float = Field(ge=0, le=10)
    novelty_score: float = Field(ge=0, le=10)
    testability_score: float = Field(ge=0, le=10)

    major_concerns: list[str] = Field(default_factory=list)

    recommendation: str


class ReviewBatch(BaseModel):
    """Reviews for a collection of hypotheses."""

    reviews: list[HypothesisReview]


class PairwiseDecision(BaseModel):
    """The result of comparing two hypotheses."""

    winner_id: str
    loser_id: str
    reasoning: str


class RankingResult(BaseModel):
    """Final ranking information after a tournament."""

    hypothesis_id: str
    elo_rating: float
    wins: int = 0
    losses: int = 0


class EvolutionBatch(BaseModel):
    """New hypotheses created from existing high-performing hypotheses."""

    hypotheses: list[Hypothesis]


class Paper(BaseModel):
    """A scientific paper retrieved from the literature."""

    id: str
    title: str
    abstract: str = ""
    publication_year: int | None = None
    doi: str | None = None
    cited_by_count: int = 0


class LiteratureResult(BaseModel):
    """Literature retrieved for a research goal."""

    papers: list[Paper] = Field(default_factory=list)


class SimilarityPair(BaseModel):
    """Conceptual similarity between two hypotheses."""

    hypothesis_a_id: str
    hypothesis_b_id: str

    similarity_score: float = Field(
        ge=0,
        le=1,
    )

    explanation: str


class ProximityResult(BaseModel):
    """Similarity analysis across a hypothesis population."""

    pairs: list[SimilarityPair]


class ResearchRoadmap(BaseModel):
    """Final synthesis produced by the meta-review agent."""

    research_goal: str

    leading_hypothesis_id: str
    leading_hypothesis_summary: str

    why_it_is_promising: list[str] = Field(default_factory=list)
    major_remaining_concerns: list[str] = Field(default_factory=list)

    alternative_hypotheses: list[str] = Field(default_factory=list)

    unresolved_questions: list[str] = Field(default_factory=list)

    recommended_experiment: str

    overall_assessment: str